name: CI
on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lintrunner-checks:
    name: Lintrunner Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659
        with:
          environments: default lint
      - name: lintrunner-init
        run: pixi run lintrunner-init
      - name: lintrunner-run
        run: pixi run lintrunner-run

  build-and-install:
    name: Build, install, test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659
        with:
          environments: default build
      - name: Build
        run: pixi run build-debug
      - name: Install
        run: pixi run install-debug
      - name: Test
        run: pixi run test
